// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAThESNdtIv1wlur0mJHrRptlvAlTIDzUc',
    appId: '1:281624548345:web:3ff57ce9ddc045f5316328',
    messagingSenderId: '281624548345',
    projectId: 'coffe-app-8740e',
    authDomain: 'coffe-app-8740e.firebaseapp.com',
    storageBucket: 'coffe-app-8740e.appspot.com',
    measurementId: 'G-JH1RPRHK11',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMUNHs-7NYbq3inZp2wOsy0Rzp6Y85gdc',
    appId: '1:281624548345:android:caec8cf2519680c2316328',
    messagingSenderId: '281624548345',
    projectId: 'coffe-app-8740e',
    storageBucket: 'coffe-app-8740e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHCnfD0bj0Zw2quCVeN3k4LmqBQGZpbgI',
    appId: '1:281624548345:ios:e1499499e53f3bfe316328',
    messagingSenderId: '281624548345',
    projectId: 'coffe-app-8740e',
    storageBucket: 'coffe-app-8740e.appspot.com',
    iosClientId: '281624548345-hu0e6o0te3c15j3ei6hf0s9t0a1usssv.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHCnfD0bj0Zw2quCVeN3k4LmqBQGZpbgI',
    appId: '1:281624548345:ios:e1499499e53f3bfe316328',
    messagingSenderId: '281624548345',
    projectId: 'coffe-app-8740e',
    storageBucket: 'coffe-app-8740e.appspot.com',
    iosClientId: '281624548345-hu0e6o0te3c15j3ei6hf0s9t0a1usssv.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookly',
  );
}
